version: "3.1"

services:
  mongodb:
    image: mongo:4.0.4
    container_name: db-apipet
    restart: always
    ports:
      - 27017:27017
      - 28017:28017
    volumes:
      - data-db-mongo:/data/db

  nodejs:
    build: .
    container_name: nodejs
    ports:
      - 8000:3333
    restart: always
    depends_on:
      - mongodb
    volumes:
      - ./backend:/usr/app

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./web:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
    depends_on:
      - nodejs

volumes:
  data-db-mongo:
